### ISSUE TITLE
Please provide full example.

### ISSUE THREAD

**Issue by alexCatena** [lifeomic/alpha#12]
This package is exactly what im looking for. However I can not seem to get the lambda url work. Please can you provide a full example.
I see that an alias is required. Does this mean that I have to explicitly declare an alias for the lambdas in my cloudformation file ?

**Comment by jagoda** [comment]
While aliases are supported they are not required. `alpha` does assume that the Lambda function supports an HTTP-style event payload structure like the one provided by [`serverless-http`](https://github.com/dougmoscrop/serverless-http). There are a few more technical details and examples in our blog: https://medium.com/lifeomic/building-lambda-based-microservices-22328ecdb7c6

Would it be possible for you to provide a code sample and the error message that you are getting?

**Comment by Druotic** [comment]
Closing since it's been nearly two years since opening. Feel free to comment or open another issue if you were unable to resolve your issue @alexCatena .
